[versions]
kotlin = "2.1.20-Beta1"
shadow = "8.1.1"
spigot = "1.21.4-R0.1-SNAPSHOT"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }