[versions]
kotlin = "2.1.20-Beta1"
shadow = "8.1.1"
bukkit = "1.10.2-R0.1-SNAPSHOT"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
bukkit-api = { group = "org.bukkit", name = "bukkit", version.ref = "bukkit" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
